### ISSUE TITLE
Bugs with PMMO

### ISSUE THREAD

**Issue by enimog** [Alexthw46/Ars-Scalaes#1]
Hello,

I encountered the following bugs when using PMMO and your mod, and I wanted to tell you how to fix them;

1) The server crash when a player launch a spell on another player
In ConfigHandler.java:34, replace LEVEL_TO_SPELL_DMG with LEVEL_TO_SPELL_RES to avoid having a null value

2) The skill is not the same as Ars Nouveau/PMMO (Ars is using Magic, yours display as pmmo.MAGIC)
In PmmoCompatEventHandler.java, replace every instance of Skill.<skill>.name with Skill.<skill>.toString()
The difference is that yours is uppercase and theirs is lowercase, which is not the same.

**Comment by Tyrius1** [comment]
https://pastebin.com/cMke3vSS
My Crash report looks similar to this.

**Comment by Alexthw46** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-scalaes/files/3831744
Let me know if Tyrius crash persist. Thanks for the heads up on 1 and 2, those were pretty dumb error i that slipped in.

**Comment by TheIvanic** [comment]
I'm getting the same crash when attempting to join a server with the mod: [Crash Report](https://paste.ee/p/rxleM)

**Comment by Alexthw46** [comment]
Uh, i understood what happens. Fix incoming.
