### ISSUE TITLE
Scalaes making the origin class layer disappear

### ISSUE THREAD

**Issue by Bastian-Fuentes** [Alexthw46/Ars-Scalaes#13]
Hello! I'm making a modpack with origins and classes in it (along many other mods), but when installing Ars Scalaes, the class layer GUI from origins stops appearing, even with the commands, the only way to get a class is by using commands

Files/Versions used:
Forge 1.20.1 47.2.32
origins-forge-1.20.1-1.10.0.9-all.jar
origins-classes-forge-1.2.1.jar
ars_nouveau-1.20.1-4.11.0-all.jar
ars_scalaes-1.20.1-1.10.3.jar

The latest log
[latest.log](https://github.com/Alexthw46/Ars-Scalaes/files/15473708/latest.log)

Unsure if it is a conflict with any other mod, since the GUI work fine without scalaes installed

**Comment by Alexthw46** [comment]
rollback to previous scalaes version for now, it seems that instead of disabling the arsificier class it disabled the entire layer... (unless it was a false alarm? unsure why the issue was instaclosed :P )
