### ISSUE TITLE
crash with malum

### ISSUE THREAD

**Issue by pibblepower** [Alexthw46/Ars-Scalaes#18]
when installing the newest version of malum, the game crashed when interacting with a mob (a evil craft silverfish). I checked the crash report, and it seems that this mod and malum may be responsible. I can't even play the world anymore, because the game crashes immediately when logging back in. Here's the crash report: 
[crash-2024-10-26_23.37.08-server.txt](https://github.com/user-attachments/files/17532704/crash-2024-10-26_23.37.08-server.txt)

**Comment by Alexthw46** [comment]
it released yesterday and made an internal renaming that broke it, hotfix should be online soon
