### ISSUE TITLE
casting magic crashes world

### ISSUE THREAD

**Issue by MoonMoonShark** [Alexthw46/Ars-Scalaes#2]
I realized that running Ars Nouveau alongside Project MMO in our server's modpack wasn't working, because they don't talk to each other, so I installed Ars Scalaes to bridge between them, but the first time I tried to cast a spell, the server shut down. I rebooted it and tried again, and again it crashed. I made a local game and had the same result.

**Minecraft:** 1.18.2
**Forge:** 40.1.68
**Ars Nouveau:** ars_nouveau-1.18.2-2.6.5.jar
**Ars Scalaes:** ars_scalaes-1.18.2-1.5v2.jar
**Curios:** curios-forge-1.18.2-5.0.7.1.jar
**GeckoLib:** geckolib-forge-1.18-3.0.29.jar
**Patchouli:** Patchouli-1.18.2-71.1.jar
**Project MMO:** Project_MMO-1.18.2-3.69.11.jar

**Modpack:** https://www.curseforge.com/minecraft/modpacks/the-lighthouse

**Crash Report:** [crash-2022-07-19_20.12.10-server.txt](https://github.com/Alexthw46/Ars-Scalaes/files/9145435/crash-2022-07-19_20.12.10-server.txt)
**Latest Log:** [latest.log](https://github.com/Alexthw46/Ars-Scalaes/files/9145433/latest.log)
**Debug Log:** [debug.log](https://github.com/Alexthw46/Ars-Scalaes/files/9145434/debug.log)

**Comment by MoonMoonShark** [comment]
I have now tried it again with ONLY the required mods, all other mods removed, and i'm still having the same crash.

**Crash Report:** [crash-2022-07-19_20.34.02-server.txt](https://github.com/Alexthw46/Ars-Scalaes/files/9145527/crash-2022-07-19_20.34.02-server.txt)
**Latest Log:** [latest.log](https://github.com/Alexthw46/Ars-Scalaes/files/9145532/latest.log)
**Debug Log:** [debug.log](https://github.com/Alexthw46/Ars-Scalaes/files/9145536/debug.log)

**Comment by Alexthw46** [comment]
as written in the changelog (i changed it now to be fully explicit), v2 only works with the reworked Pmmo, aka the pmmo 2.x.x version marked as alpha.
You need to use the other version, ars_scalaes-1.18.2-1.5 (suggested), or upgrade to that alpha version (will wipe current configs).

**Comment by MoonMoonShark** [comment]
i see. it just said "latest version" and as far as i knew, i was using the latest version of all mods. i appreciate the clarification. :)
