### ISSUE TITLE
PMMO updated to v4 breaks Ars Scalaes Rework

### ISSUE THREAD

**Issue by MoonMoonShark** [Alexthw46/Ars-Scalaes#4]
Minecraft: 1.18.2
Forge: 40.1.84
PMMO: pmmo-1.18.2-4.0.0.jar
Ars Nouveau: ars_nouveau-1.18.2-2.8.0.jar
Ars Scalaes: ars_scalaes-1.18.2-1.7b-rework.jar

oh man! so excited! PMMO 1.18.2 finally rolled out the reworked version! unfortunately they went with a different version number than was expected by Ars Scalaes.

![image](https://user-images.githubusercontent.com/57743121/201678250-6b38617b-0254-4bf3-bbec-7a864a7e8ab4.png)

**Comment by Alexthw46** [comment]
Yeah, and it comes with an API change, so it would have crashed anyway :P
I'll upload the patch soon

**Comment by Alexthw46** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-scalaes/files/4086670
When the link start working, there you are

**Comment by MoonMoonShark** [comment]
huzzah! thank you!!!! :D
